version: "3.8"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                BACKEND_PORT: ${BACKEND_PORT}

        ports:
            - "${BACKEND_PORT}:${BACKEND_PORT}"

        environment:
            BACKEND_PORT: ${BACKEND_PORT}
